### PR TITLE
V1 progress

### LINKED ISSUE #4: Suggestion: db.row for selecting single row
To read a single row with tiny_sqlite, I used:
```
for row in db.rows("select v from t where k = 13"):
  let (v,) = row.unpack((int,))
  echo v
```
It seems a little odd to me because the for + db.rows implies processing multiple rows.  Maybe it could be made clearer by adding a break to the end.

A simpler, and I think clearer alternative would be something like:
```
  let (v,) = db.row("select v from t where k = 13").unpack((int,))
```
I added this to my copy of tiny_sqlite and it works fine:
```
proc row*(db: DbConn, sql: string,
          params: varargs[DbValue, toDbValue]): seq[DbValue] =
    ## Executes ``sql`` and returns 1 row.
    for row in db.rows(sql, params):
        return row
```
Here's the original test program using db.rows:
```
import os
import tiny_sqlite

const
  dbname = "bttest4.nim.db"

let nrows = 1_000_000
#let nrows = 100
os.removeFile(dbname)

let db = openDatabase(dbname)

db.exec("""create table t (
  k    integer primary key,
  v    integer)""")

db.transaction:
  for i in 0..<nrows:
    db.exec("insert into t values (?,?)", i, i)

db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      for row in db.rows("select v from t where k = ?", j):
        let (v,) = row.unpack((int,))
        db.exec("update t set v = ? where k = ?", v+1, j)

for row in db.rows("select v from t where k = 13"):
  let (v,) = row.unpack((int,))
  echo v

db.close()
```
Here's a snippet from the new version, to get a visual of the difference.  It's only 2 lines shorter but looks clearer to me:
```
db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      let (v,) = db.row("select v from t where k = ?", j).unpack((int,))
      db.exec("update t set v = ? where k = ?", v+1, j)

let (v,) = db.row("select v from t where k = 13").unpack((int,))
echo v
```
Mistakenly switching db.row and db.rows could be a source of bugs, but db.1row isn't legal, and db.aRow, db.oneRow, and db.singleRow seem a little much.

Another option could be something like db.unpackRow that accepts a query string:
```
let (v,) = db.unpackRow("select v from t where k = 13", (int,))
echo v
```
That's not as flexible because you can't get the row itself.  Nim's db_sqlite has GetValue to read the first value from a row, but that won't work for a multi-value row, like selecting count(*), avg(size).

### PR DESCRIPTION
**Pull request by GULPF**
Closes #4

### CODE REVIEW

**Comment by hashbackup** [comment]
These changes look really great.  I like the .strval syntax for db.one to get a single value vs unpack, and also being able to address columns by name.  I do this _all over_ HashBackup with pysqlite, because it is not always convenient to use the f1, f2 = db.rows(...) syntax, especially if the query selects 5-10 fields, but different fields are needed in different situations.  Plus it prevents having to create a lot of local variables named like db fields.

I'm not so sure about having prepared stmts be their own thing, but will play around with my test program.  Personally, I think it's simpler that the user doesn't have to think about prepared statements if they don't want to.  I can see a slight advantage to exposing a stmt type, because it avoids the table lookup in the cache, but IMO, it also makes application code less clear because the query string and the query parameters are separated.  So instead of just look at an exec that contains the query string + parameters, you see somestmt.exec(blah1, blah2) and have to go lookup somestmt to see what it is.  Plus, I can't think of an example where it would be necessary to bypass the prepared stmt cache, unless perhaps the schema changed, but to handle that, a new proc could clear the cache.

Thanks again for you effort on this - very nice!

**Comment by hashbackup** [comment]
So far I have not had much luck with this new version.  The test program is here:
```
import os
import tiny_sqlite

const
  dbname = ":memory:"

let nrows = 1_000_000
#let nrows = 100
os.removeFile(dbname)

let db = openDatabase(dbname)

db.exec("""create table t (
  k    integer primary key,
  v    integer)""")

db.transaction:
  for i in 0..<nrows:
    db.exec("insert into t values (?,?)", i, i)

db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      for row in db.rows("select v from t where k = ?", j):
        let (v,) = row.unpack((int,))
        db.exec("update t set v = ? where k = ?", v+1, j)

for row in db.rows("select v from t where k = 999999"):
  let (v,) = row.unpack((int,))
  echo v

db.close()
```
If I compile + run this with the new library unchanged, I get this:
```
s:nx jim$ nim c bttest5
/Users/jim/nx/bttest5.nim(21, 3) template/generic instantiation of `transaction` from here
/Users/jim/nx/bttest5.nim(24, 21) Warning: use 'all' instead; rows is deprecated [Deprecated]
/Users/jim/nx/bttest5.nim(21, 3) template/generic instantiation of `transaction` from here
/Users/jim/nx/bttest5.nim(25, 24) Warning: unpack is deprecated [Deprecated]
/Users/jim/nx/bttest5.nim(21, 3) template/generic instantiation of `transaction` from here
/Users/jim/nx/bttest5.nim(24, 21) Warning: use 'all' instead; rows is deprecated [Deprecated]
/Users/jim/nx/bttest5.nim(21, 3) template/generic instantiation of `transaction` from here
/Users/jim/nx/bttest5.nim(25, 24) Warning: unpack is deprecated [Deprecated]
/Users/jim/nx/bttest5.nim(28, 15) Warning: use 'all' instead; rows is deprecated [Deprecated]
/Users/jim/nx/bttest5.nim(29, 18) Warning: unpack is deprecated [Deprecated]
Hint: 42714 LOC; 1.216 sec; 57.898MiB peakmem; Debug build; proj: /Users/jim/nx/bttest5; out: /Users/jim/nx/bttest5 [SuccessX]

ms:nx jim$ /usr/bin/time -l ./bttest5
1000002
       60.57 real        60.54 user         0.03 sys
  27496448  maximum resident set size
```
If I use the old version of tiny_sqlite with prepared stmt caching, I get this:
```
ms:nx jim$ nim c -d:danger bttest5
Hint: 41009 LOC; 1.386 sec; 58.324MiB peakmem; Dangerous Release build; proj: /Users/jim/nx/bttest5; out: /Users/jim/nx/bttest5 [SuccessX]

ms:nx jim$ /usr/bin/time -l ./bttest5
1000002
       14.62 real        14.59 user         0.02 sys
  27389952  maximum resident set size
```
I've also been trying to modify the test to remove the deprecated features, but not having much luck with that yet either.  Can't get it to compile, but I will re-read the docs a few times and keep experimenting.  I spent hardly any time getting the test program to work with the old setup.  I tried this but it doesn't compile (I also tried using `fromDbValue(v.get, int)` but that didn't work either):
```
      var v = db.value("select v from t where k = ?", j)
      v = fromDbValue(v, int)
```

I took a brief look at the new tiny_sqlite code (I'm new to Nim, so still get easily confused!)  It looks like if prepareSql gets called with args, it caches the prepared stmt.  But if it gets called with just an sql string, it doesn't cache.  That doesn't seem correct, because I could have a query like "select * from blah where a < b" that has no parameters, yet should still be cached to avoid recompiling it every time it is encountered.  Something weird is going on, because the test program runs 4x slower now that it did before.

I'll post an update if I figure anything out.

**Comment by hashbackup** [comment]
Sorry, I did a regular compile instead of -d:danger with the new version.  Now it runs in 17.69s, so slightly slower than before, but more or less in the ballpark.

**Comment by hashbackup** [comment]
I got the new version to run using the old unpack syntax.  Trying to use the newer stuff I didn't have much luck.  Here are some of my recent attempts.  Maybe this will help you understand where some documentation change might help, or maybe you just need smarter users than me! ;-)
```
      let row = db.one("select v from t where k = ?", j)
      let (v,) = row.unpack((int,))    # fails
#      let v = fromDbValue(row[0], int)   # fails  
#      let v = row[0].intVal  # fails
```

**Comment by GULPF** [comment]
@hashbackup Thanks for all the feedback!

> I got the new version to run using the old unpack syntax. Trying to use the newer stuff I didn't have much luck. Here are some of my recent attempts. Maybe this will help you understand where some documentation change might help, or maybe you just need smarter users than me! ;-)

The issue is that `one` and `value` returns the result wrapped in an [Option](https://nim-lang.org/docs/options.html), to represent the case where the SQL statement found no rows. The option must first be unpacked before `unpack`/`fromDbValue` are used, e.g `row.get.unpack((int,))`. I will try to clarify this better in the documentation.

Here is an updated version of the performance test:
```nim
import tiny_sqlite
import options

const
  dbname = ":memory:"

let nrows = 1_000_000
let db = openDatabase(dbname)

db.exec("""create table t (
  k    integer primary key,
  v    integer)""")

db.transaction:
  for i in 0..<nrows:
    db.exec("insert into t values (?,?)", i, i)

db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      for row in db.iterate("select v from t where k = ?", j):
        db.exec("update t set v = ? where k = ?", row[0].intVal+1, j)

let v = db.value("select v from t where k = 999999").get.fromDbValue(int)

db.close()
```

Somewhat worse performance is to be expected since it now keeps track of the column names, but I'll see if I can improve it. Currently it stores the column names in each individual `ResultRow` which is wasteful. Note that you can use the new gc modes `--gc:arg` and `--gc:orc` to get some speedup, see https://forum.nim-lang.org/t/5734 for details.

> I'm not so sure about having prepared stmts be their own thing, but will play around with my test program. Personally, I think it's simpler that the user doesn't have to think about prepared statements if they don't want to. I can see a slight advantage to exposing a stmt type, because it avoids the table lookup in the cache, but IMO, it also makes application code less clear because the query string and the query parameters are separated. So instead of just looking at an exec that contains the query string + parameters, you see somestmt.exec(blah1, blah2) and have to go lookup somestmt to see what it is. Plus, I can't think of an example where it would be necessary to bypass the prepared stmt cache, unless perhaps the schema changed. To handle that, a new proc could clear the cache.

I generally agree and I probably won't use the prepared statement API in my own code, but I wanted to include it for completeness for those preferring to cache statements themselves. The built in cache has the disadvantage that it's a bit unpredictable since you might not know if a statement is cached or not. It also causes more memory usage since even statements that are only used once will be included in the cache.

> I took a brief look at the new tiny_sqlite code (I'm new to Nim, so still get easily confused!) It looks like if prepareSql gets called with args, it caches the prepared stmt. But if it gets called with just an sql string, it doesn't cache. That doesn't seem correct, because I could have a query like "select * from blah where a < b" that has no parameters, yet should still be cached to avoid recompiling it every time it is encountered. Something weird is going on, because the test program runs 4x slower now that it did before.

The overload without arguments is only called for the prepared statement API, in which case the built in cache should not be used.

**Comment by hashbackup** [comment]
Thanks for the tips.  A couple other things I found out before seeing your tips:
* the docs say to see the options module (which I admit I didn't go read; I was just trying to go by the examples), but I didn't realize that I needed to import options, because I am neoNim.  I don't know if it makes sense for import tiny_sqlite to shove the options module into my namespace (with export?), or maybe just add a note that the options module must also be imported with iny_sqlite for the dummies like me
* the deprecation warning about replacing rows with all, I think is not correct, at least not in all situations.  When I replaced db.rows with db.all, the runtime was 17.98 secs.  When I replaced db.rows with db.iterate, it went down to 16.28 secs, even though for this test it is only fetching 1 row.  For a query returning lots of rows, the difference will probably be even higher since all creates a large sequence.  I think the dep warning should say to use iterate instead of rows (like you did in your post), not all.

**Comment by hashbackup** [comment]
I understand a little better now.  Python's sqlite3 has a similar situation when you do something like:
```
sum = db.con.execute('select sum(x) from logs').fetchone()[0]
```
You can do fetchone[0] because that query will usually work, but on an empty table, fetchone() returns None so it bombs trying to index None.  Subtle bug.  I had wondered about how this was handled with the old API.

To help me understand this better, I changed the last query to db.one and started echoing first the returned row, then row.get, then row.get["v"], then row.get["v"].intVal.  Is there a reason why anyone would want to use fromDbValue(int) instead of .intVal?  One of the things that's a bit confusing is there are several ways to do the same thing, which raises the question "why would I want to use x instead of y?"  Plus one way uses int and the other uses intVal.  It would be simpler to just use .int (fewer things to remember), but maybe that's not possible.  And if it's not ever necessary to use `fromDbValue(int)`, I'd leave it out because it's a pain to type vs `.intVal`.

This seems to work now:
```
let row = db.one("select v from t where k = 9999")
if row.isSome:
  echo row.get["v"].intVal
else:
  echo "No row found"
```
It might help to explain in the docs that if you do row.get without first checking isSome, and the query did not return any rows, you'll get:
```
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]
```
So if you *know* the query will work, it's okay to avoid the if isSome check.  This will be familiar to Python sqlite3 users and maybe help them understand why both rows and values (I think) are getting wrapped in Option: rows because rows might not be returned, and values because of null column values.

I was wrong about the size of the sqlite3 cache: it's 100 stmts, not 50.  Might be a good idea to use 100 to avoid a situation where a set of queries runs fine with sqlite3 but is slower with Nim because the cache is thrashing.  Honestly, I've never checked to see if I'm thrashing the sqlite3 stmt cache.  A note about how to display the size of the cache might be useful.

sqlite3 uses an LRU cache whereas tiny is using a FIFO.  If it's just as easy, an LRU cache would help address your point about needing to manually prepare stmts to avoid cache unpredictability since stmts that are only used once will be thrown out of an LRU cache more quickly.
 
The way sqlite3 handles column names is by making them a cursor attribute vs row, and you can access the names with cursor.keys(), though I have never used that.  But I can see where adding the names to every returned row, especially for a large select, would be less efficient than keeping the names attached to the prepared statement.

This is a small thing, but as I was reading through the sqlite3 doc, it mentioned that it only uses the first word of the column name.  If you do something like `select blah as "x z y"` sqlite3 will use a column name of x.  I tested this with tiny and it uses the full column name "x y z", which to me is more correct, but it might (or might not) be worth a footnote.

The wording that confused me about prepared stmts is this in the documentation:
```
All the procedures described above operate directly on the database connection. In addition to those procedures, tiny_sqlite also offer an API for preparing SQL statements in advance. 
```
The "directly on the database connection" part implied to me that db.exec() does not go through the cache, especially since we are in the section talking about how to use a different API to prepare stmts.  I can try to do a pull request with some alternate wording, though my GH skills are even worse than my Nim skills.

As a more general thing, I like how Nim can generate details documentation from source.  But it does that based on the topological order required by the Nim compiler: imports, types, and procs, all ordered from "least dependencies" to "most dependencies", ie, bottom-up.  But most people tend to grasp ideas better when higher-level concepts are presented first, with lower-level concepts (like the 13 dbFrom/ToValues) presented last.  Maybe there is some automagic way the documentation could be reordered to be top-down, from most dependencies to least dependencies.  Just an idea - might work, might not.

Thanks again, this is looking good!

**Comment by hashbackup** [comment]
Using this in the loop:
```
      let v = db.one("select v from t where k = ?", j).get["v"].intVal
```
Takes 17.31s.  Using this:
```
      let v = db.value("select v from t where k = ?", j).get.intVal
```
Takes 16.01s, just FYI.

**Comment by hashbackup** [comment]
Here are some runs with no options, -d:useMalloc, --gc:arc FYI.  This is on an idle i7 Mac Mini but it looks like there is some background noise. 
```
ms:nx jim$ nim c -d:danger x
Hint: 42720 LOC; 1.367 sec; 58.41MiB peakmem; Dangerous Release build; proj: /Users/jim/nx/x; out: /Users/jim/nx/x [SuccessX]

ms:nx jim$ /usr/bin/time -l ./x
102
       16.11 real        16.08 user         0.01 sys
  27381760  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       16.00 real        15.98 user         0.02 sys
  27435008  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       15.66 real        15.63 user         0.02 sys
  27320320  maximum resident set size
```
```
ms:nx jim$ nim c -d:danger -d:useMalloc x
Hint: 42720 LOC; 1.370 sec; 58.395MiB peakmem; Dangerous Release build; proj: /Users/jim/nx/x; out: /Users/jim/nx/x [SuccessX]

ms:nx jim$ /usr/bin/time -l ./x
102
       15.73 real        15.70 user         0.01 sys
  27340800  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       15.91 real        15.89 user         0.01 sys
  27332608  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       15.37 real        15.34 user         0.02 sys
  27361280  maximum resident set size
```
```
ms:nx jim$ nim c --gc: arc -d:danger x         
Hint: 40447 LOC; 1.212 sec; 58.465MiB peakmem; Dangerous Release build; proj: /Users/jim/nx/x; out: /Users/jim/nx/x [SuccessX]

ms:nx jim$ /usr/bin/time -l ./x
102
       15.92 real        15.90 user         0.01 sys
  27246592  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       15.78 real        15.75 user         0.01 sys
  27205632  maximum resident set size

ms:nx jim$ /usr/bin/time -l ./x
102
       15.97 real        15.95 user         0.01 sys
  27246592  maximum resident set size
```

**Comment by hashbackup** [comment]
I changed prepareSql to simulate an LRU cache, like this:
```
proc prepareSql(db: DbConn, sql: string, params: seq[DbValue]): sqlite.Stmt
        {.raises: [SqliteError].} =
    if db.cacheSize > 0:
        result = db.cache.getOrDefault(sql)
        if not result.isNil:
            db.cache.del sql
    if result.isNil:
        result = prepareSql(db, sql)
    if db.cacheSize > 0:
        db.addToCache(sql, result)
    let rc = db.bindParams(result, params)
    db.checkRc(rc)
```
The runtime increased from 16s to 22s for the test above, about 7M SQL commands.

My intuition is that it's smarter to increase the cache size to handle all queries rather than use a smaller cache with LRU.

**Comment by hashbackup** [comment]
Also tried jackhftang/lrucache.nim, like this:
```
ms:nx jim$ diff -C 1 tiny_sqlite.nim.1 tiny_sqlite.nim
*** tiny_sqlite.nim.1	Sat Jul 11 16:29:46 2020
--- tiny_sqlite.nim	Sat Jul 11 16:39:32 2020
***************
*** 4,5 ****
--- 4,6 ----
  from tiny_sqlite / sqlite_wrapper as sqlite import nil
+ import lrucache
  
***************
*** 8,10 ****
          handle: sqlite.Sqlite3 ## The underlying SQLite3 handle
!         cache: OrderedTable[string, sqlite.Stmt]
          cacheSize: int
--- 9,11 ----
          handle: sqlite.Sqlite3 ## The underlying SQLite3 handle
!         cache: LruCache[string, sqlite.Stmt]
          cacheSize: int
***************
*** 66,68 ****
  template db(statement: SqlStatement): DbConn = SqlStatementImpl(statement).db
! template cache*(db: DbConn): OrderedTable[string, sqlite.Stmt] = DbConnImpl(db).cache
  template cacheSize*(db: DbConn): int = DbConnImpl(db).cacheSize
--- 67,69 ----
  template db(statement: SqlStatement): DbConn = SqlStatementImpl(statement).db
! template cache*(db: DbConn): LruCache[string, sqlite.Stmt] = DbConnImpl(db).cache
  template cacheSize*(db: DbConn): int = DbConnImpl(db).cacheSize
***************
*** 96,102 ****
      db.cache[sql] = prepared
-     if db.cache.len > db.cacheSize:
-         for k, v in db.cache:
-             discard sqlite.finalize(v)
-             db.cache.del k
-             break
  
--- 97,98 ----
***************
*** 240,242 ****
      if db.cacheSize > 0:
!         result = db.cache.getOrDefault(sql)
      if result.isNil:
--- 236,238 ----
      if db.cacheSize > 0:
!         result = db.cache.getOrDefault(sql, nil)
      if result.isNil:
***************
*** 561,562 ****
--- 557,559 ----
      db.cacheSize = cacheSize
+     db.cache = newLruCache[string, sqlite.Stmt](cacheSize)
      result = DbConn(db)
```
Not sure I did it all right (there's no iterator to dump the cache), but here are the runtimes with -d:danger:
```
ms:nx jim$ /usr/bin/time -l ./x
DbValue[102]
Cache size = 100, cached items = 7
       16.30 real        16.27 user         0.02 sys
  27430912  maximum resident set size
```

**Comment by hashbackup** [comment]
I think the reason my hacked-up LRU cache was so slow is because Nim's OrderedTable (OT) is really bad for deletes: every delete is O(n) and to make things worse, creates a new table. I said I didn't think an LRU cache was worth it but now have changed my mind based on tests and think tiny_sqlite should use LruCache instead of OT.  I'm going to post an issue on GH for OT and propose changing it to use something similar to LruCache above, which is O(1) and very fast.  For tiny_sqlite, OT would work fine until the cache is full and starts thrashing.  This could happen for example if someone were doing their own string interpolation instead of using sql placeholders.  Then on every sql operation OT would recreate the entire cache.

**Comment by GULPF** [comment]
@hashbackup I've opened a new PR that addresses your feedback: #7

**Pull request merged**
